issues:
  max-per-linter: 0
  max-same-issues: 0

# golangci-lint run --print-issued-lines=false --uniq-by-line=false --no-config --enable-all 2> /dev/null | awk 'NF>1{print $NF}' | tr -d '()' | sort -u
linters:
  enable-all: true
  disable:
  - depguard
  - exhaustivestruct
  - exhaustruct
  - funlen
  - godot
  - godox
  - interfacer
  - lll
  - perfsprint
  - revive
  - wrapcheck
  - wsl
