version: "2"
linters:
  default: all
  disable:
  - depguard
  - exhaustruct
  - funcorder
  - funlen
  - godox
  - lll
  - noinlineerr
  - perfsprint
  - recvcheck
  - revive
  - wsl
  - wsl_v5
  settings:
    varnamelen:
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true
