version: 3

images:
  base_image:
    name: ghcr.io/ansible/community-ansible-dev-tools:v25.5.2

additional_build_steps:
  prepend_final:
  - RUN dnf install -y openssh-clients awscli2
  - RUN dnf install -y https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm
