# ansible-builder build --container-runtime=<podman or docker> -t <container image tag> --no-cache
version: 3

images:
  base_image:
    name: docker.io/fedora:41

dependencies:
  python:
  - jmespath==1.0.1
  - ansible-lint==24.2.0

  ansible_core:
    package_pip: ansible==9.3.0
  ansible_runner:
    package_pip: ansible-runner==2.3.5

additional_build_steps:
  prepend_final:
  - RUN dnf install -y openssh-clients awscli2
  - RUN dnf install -y https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm
